FROM node:16-alpine

WORKDIR /app


#copy as source code from ./
COPY package*.json ./


RUN npm install && npm install -g serve

COPY  . .

ENV REACT_APP_BASE_URL=http://localhost:5001

ENV PORT=3000

EXPOSE 3000



RUN npm run build

#CMD [ "npm", "start" ]

CMD serve -s build